### PR TITLE
add Aopt

### PR DESCRIPTION
**Pull request by Surge1223**
Add Aopt and merge changes from android-7.0.0_r1 aapt/androidfw updates

### CODE REVIEW

**Comment by CurioZuk** [comment]
@Surge1223

**Comment by Surge1223** [comment]
No one wants to discuss?  AOPT is just AAPT renamed so that I could keep dependencies seperate. 
Libaoptfw is just a static androidfw,  I didn't want to modify any files in fwbase i didn't have to,  but we needed to make androidfw static,  plus this way any modifications don't effect androidfw. 

Other than that,  and some elite Android.mk editing,  just need a few static libs.  Most significant of which is libc++ so I switched to gnu++14 so I could use a few newer functions/standards,  like iostream and a few others. 

Wanted this to be static so that it would not depends on system libs.  

Discuss.

**Comment by nicholaschum** [comment]
@Surge1223 Does this version of AOPT limit the creation of Java apks?

**Comment by Surge1223** [comment]
No.  I figured id include the full suite before we neutered it lol.  Also the options for modifying java can be removed simply front commenting out the optflag in Main.cpp.

I should note,  I don't even know how to use AAPT/AOPT.  Maybe someone like slim or cm who depend on  custom configurations can chime in.

**Comment by nicholaschum** [comment]
@Surge1223 Well, don't worry. I know how to use aapt. As long as we know which file to modify to easily block off these commands from running, then we can pull it.

**Comment by Surge1223** [comment]
what commands allow creation of Java files?  Also don't we need to be able to regen R.java?

**Comment by nicholaschum** [comment]
@Surge1223 I don't have access to aapt atm, but do aopt —help, and find commands that compile "dex" or "java", as well as "from zip"

**Comment by nicholaschum** [comment]
Added to Gerrit for further code review:

http://review.projektsubstratum.com/#/q/status:open+project:TeamSubstratumResources/platform_frameworks_base+branch:android-7.0.0_r1+topic:aopt-integrate

**Pull request closed without merging**
